### ISSUE TITLE
Tests on the robot

### ISSUE THREAD

**Issue by giuliavezzani** [tacman-fp7/handover#25]
This is to collect tests performed on the robot

**Comment by giuliavezzani** [comment]
### Online Tests on the Blacky: ToDo List

- [x] install new code and suitably update the config files (robot name, online mode etc..)

- [x] **fine** arms and head **calibration**

- [x]  **SFM** calibration

- [ ] **depth2kin** calibration

- [x] test @massimoregoli's code in order to select at least two objects (sugar box for sure)

- [x] acquire and check **point clouds** at least of one object in **left hand** and **right hand**

- [x] pose selection and closed chain with the box **without moving the second hand** 

- [x] pose selection and approach with the box **moving the second hand** 

### Offline Tests: ToDo List

- [x] analyze **point clouds** collected with the object in the **right hand**

- [x] test pose selection and closed chain with the **left hand moving**

- [x] annotate the **new** selected **object** model with 8 **poses**

- [x] test **pose selection** and closed chain with the **new object** on the simulator (and if possible, on the robot)

**Comment by giuliavezzani** [comment]
## Results 1.0
It's useful to summarize out pipeline weaknesses:

### External modules

- **SFM** lacking robustness

- **depth2kin** turns out to be necessary - too big errors between kinematics and vision

- **depth2kin** cannot be launched (see [icub-main #409](https://github.com/robotology/icub-main/issues/409))

### Internal modules

- we need a  very **stable** grasp of the first hand, i.e.:
       1. fingers moving as less as possible
        2. object surface that can be seen from the robot viewpoint should be the maximum one

**Comment by massimoregoli** [comment]
Regarding the grasp stability, we actually noticed that sometimes, even if the grip strength has been increased, the index or middle finger pushes more than the other and this can make the object rotate when a small perturbation is applied (sometimes even without any perturbations). In my opinion such problem can be faced in different ways:
* taking into account the difference of sensitivity between the fingers (we may have a very strong grip, but just between two fingers, so object rotations may occur),
* increasing the distance between the index and middle finger (changing the hand abduction joint angle),
* preventing the force requested at each finger from going below a given threshold: it is possible that in this way the final object position will be a little inaccurate, and that the high level controller performances won't keep exactly the same, but I think it is worth trying.

About the other requirement that @giuliavezzani mentioned:

> 2. object surface that can be seen from the robot viewpoint should be the maximum one

Actually, now that the thumb pushes more than before against the object, it may slide down (according to the specific object and on the way it is given to it) leading to an object rotation (see picture).

![](https://cloud.githubusercontent.com/assets/10046589/21937197/9b8df0e0-d9b6-11e6-896e-22cd9e29deb6.jpg)


In this case, from the iCub point of view only the top of the box can be seen. A few ways to prevent this rotation are:
* using not slippery objects
* restoring the PID integral gain of the thumb abudction joint: it had been disabled to avoid sudden unwanted thumb movements
* bypassing the GMM regression and setting manually a specific object position, so that the object inclination is the one desired (moving the object position generally causes rotations)

I applied the second and third solution and actually most of times the object inclination was the one desired (still, the actual final inclination may depend on the way the object is given to the iCub), the following picture shows the iCub point of view.

![](https://cloud.githubusercontent.com/assets/10046589/21937210/ac7ef17e-d9b6-11e6-8a4e-75409a74e54d.jpg)

**Comment by giuliavezzani** [comment]
## Results 1.1

Here are the results and comments of the [tests](https://github.com/tacman-fp7/handover/issues/25#issuecomment-271921011) performed on the robot.

### Online tests on the robot:

- **SFM** is not robust but, even if sometimes the disparity map looks quite awful, the point cloud are not so bad 

![disp blob](https://cloud.githubusercontent.com/assets/9597070/21989353/dde30dd0-dc0a-11e6-90f0-7fa6792f1c4f.png)
- **depth2kin** can be now compiled (but I have not managed to test it yes)
- @massimoregoli's code is now pretty good :smile: The **grasp is stable** and I managed to get a quite extended point cloud:

![object-pose](https://cloud.githubusercontent.com/assets/9597070/21989368/eff02be8-dc0a-11e6-96e5-bd2f9a17d46b.png)
 - **pose selection** with closed-chain. In the following picture, the **selected pose** is no. **6**. The pose on the right is the final pose to be reached by the right hand. At the same time, the left hand should move so that the highlighted pose no. 6 attached to the object model totally overlap with the pose on the right.

![handover-5](https://cloud.githubusercontent.com/assets/9597070/21989505/6e741f24-dc0b-11e6-85c3-6a7a022afd1a.png)

- an example of (failed) [handover test](https://massimo-regoli-iit.tinytake.com/sf/MTI3MTM3NV80NzcyMDc0) 

#### Comments on online tests

- a robust **approach** design is fundamental (see the previous video)
- we can try moving the **two arms separately**
- code debugging to be done
- one good point :smile: : the grasp designed by @massimoregoli is very stable!

### Offline tests

- handover code works fine also with **right hand as first hand** on the simulator

**Comment by giuliavezzani** [comment]
## Results 2.0

I tested the [**new approach**](https://github.com/tacman-fp7/handover/issues/27#issuecomment-273775015) strategy on the robot.
Unfortunately, I **didn't get point clouds good enough** to correctly localize the object. Thus, I couldn't properly test my code.
However, I'm quite confident that, **once a good localization will be provided**, **the proposed approach** **is likely to work.**

Hereafter I listed all the problems I faced and the results that make me quite optimistic about the future.

### Problems

- **SFM** performance are **random**.  This is the best point cloud I got with `vergence=5`, calibrated cameras and calibrated SFM:

![pc-example](https://cloud.githubusercontent.com/assets/9597070/22203790/02310c78-e16f-11e6-8a11-e3f3a93aa821.png)

 I also noticed that **SFM** performance seems to be better for object on the table than objects in the robot hands (and then closer to the eyes). The following figure show disparity map while the robot is looking at the object (on the left), while the robot is looking at the object in its hand very close to the table (in the middle) and while the robot is looking at the object very close to its eyes:

![sfm](https://cloud.githubusercontent.com/assets/9597070/22204036/364ee43e-e170-11e6-9a17-abb64892d625.png)

- I had some problems in making the robot correctly reach the waypoints: the solution computed by the cartesian solver provides a different orientation from the desired one. I solved the problem by following the example provided [here](https://github.com/towardthesea/karmaWYSIWYD/blob/master/src/karmaMotor/main.cpp#L612). The orientation is kept fixed and the desired positions are reached by setting the joints velocities with [setTaskVelocity()](http://www.yarp.it/classyarp_1_1dev_1_1ICartesianControl.html#a3e28664529fafbe051bce0270a2d510d) and with a proper direction during the approach.

### (Quite) Good Results

- **Moving the robot arms separately** seems to be enough in making the robot prevent hitting the object with the second hand. The general pipeline could be:
      - put the **first hand in the final position**
      - move the **second hand** toward the **final position**, passing by the **waypoints**

- the best pose and the waypoints are correctly selected 
- all the introduced parameters seem to be enough to design a good approaching strategy

Here are some examples of selected poses and computed waypoints:
-  `n_waypoint=1`, `theta=-20.0`, `offst_x_final=0.03`, `offst_z_final=0.03`, `offst_x_approach=0.08`, `offst_z_approach=0.08`

![2101-2](https://cloud.githubusercontent.com/assets/9597070/22204309/98d32a9c-e171-11e6-84f0-23c1ed718b2e.png)

-  `n_waypoint=1`, `theta=-40.0`, `offst_x_final=0.03`, `offst_z_final=0.03`, `offst_x_approach=0.08`, `offst_z_approach=0.08`

![2101-4](https://cloud.githubusercontent.com/assets/9597070/22204401/1682301e-e172-11e6-91e2-91b9ac30eaf9.png)

Finally, you can find an example of a sort of performed handover at [this link]() (it actually worked by chance.

###  :exclamation:  Warning :exclamation: 

In my option,  the main point to be addressed is to **improve point cloud quality**.

**Comment by pattacini** [comment]
Hi @giuliavezzani 

Regarding the use of `setTaskVelocity()`, there must be still something else.
This method, in fact, does also call in turn the solver, hence direct calls to solver should work as well.

**Comment by giuliavezzani** [comment]
From what I understood, [the function  I used as example](https://github.com/towardthesea/karmaWYSIWYD/blob/master/src/karmaMotor/main.cpp#L612) accomplishes the following steps:
- a direction of movement is decided: `dir`
-  the error `e` between the current position and the desired one is computed, by using information on the positions coming from the  `getPose()`  function
- then, the function `minJerkVelCtrlForIdealPlant::computeCmd()`  provides the joints velocities necessary for moving the arm, once they are properly multiplied for the desired approaching direction
- then, those velocities are imposed with the `setTaskVelocities()`
These steps are executed until the norm of the error is lower a threshold.

Maybe I misunderstood how this code and the related functions work, but actually the arm behaves as I want: the desired positions are reached moving the arm along the desired direction and without changing the initial orientation.

**Comment by pattacini** [comment]
`minJerkVelCtrlForIdealPlant::computeCmd()` provides velocities in the operational space, not in the joint space. It's a mere filter. Then these velocities are translated in the joint space through `setTaskVelocities()`, which in turn calls the solver underneath. That's why I was saying it must work also with simple calls to the solver.

**Comment by pattacini** [comment]
Anyway, if it's working with `setTaskVelocities` is fine 😃 
Let's not loose time debugging other stuff.

**Comment by giuliavezzani** [comment]
## Results 2.1

Some updates after new tests on the robot;

- **SFM** with **`sgbm`** option  is quite good (and then object localization is better than the previous tests). This is an example of the disparity map for the object:

![2401-15-sfm](https://cloud.githubusercontent.com/assets/9597070/22247942/9eae9246-e23c-11e6-9575-0a6e166665ff.png)

- I managed to obtain some reasonable movements, even if handover was not perfect:

![steps 1](https://cloud.githubusercontent.com/assets/9597070/22248183/b0fd9964-e23d-11e6-8ec2-f46c3da272a4.png)


[Click here](https://massimo-regoli-iit.tinytake.com/sf/MTI5MTM0M180ODE1MjM1) for the video of the best handover I obtained

## How to Improve

1. Intensively test **`localizer`**
2. **`depth2kin`** calibration
3. automatic check on the **blob**
4. improvements in **iCub movements**
5. tune approaching strategy **parameters**
